<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" total="2" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="TestSuite" duration-ms="115971" started-at="2016-02-03T07:36:14Z" finished-at="2016-02-03T07:38:10Z">
    <groups>
    </groups>
    <test name="FirefoxTest" duration-ms="59424" started-at="2016-02-03T07:36:14Z" finished-at="2016-02-03T07:37:14Z">
      <class name="com.mycompany.autotest.TestNGTest">
        <test-method status="PASS" signature="setUp(java.lang.String)[pri:0, instance:com.mycompany.autotest.TestNGTest@735b478]" name="setUp" is-config="true" duration-ms="4593" started-at="2016-02-03T14:36:14Z" finished-at="2016-02-03T14:36:19Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Firefox]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="testAuto()[pri:0, instance:com.mycompany.autotest.TestNGTest@735b478]" name="testAuto" duration-ms="54109" started-at="2016-02-03T14:36:19Z" finished-at="2016-02-03T14:37:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAuto -->
        <test-method status="FAIL" signature="tearDown()[pri:0, instance:com.mycompany.autotest.TestNGTest@735b478]" name="tearDown" is-config="true" duration-ms="0" started-at="2016-02-03T14:37:13Z" finished-at="2016-02-03T14:37:13Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[java.lang.AssertionError: expected [KẾT QUẢ CHIẾN DỊCH123] but found [KẾT QUẢ CHIẾN DỊCH]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: java.lang.AssertionError: expected [KẾT QUẢ CHIẾN DỊCH123] but found [KẾT QUẢ CHIẾN DỊCH]
	at org.testng.Assert.fail(Assert.java:94)
	at com.mycompany.autotest.TestNGTest.tearDown(TestNGTest.java:272)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeAfterClassMethods(TestMethodWorker.java:225)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:114)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.mycompany.autotest.TestNGTest -->
    </test> <!-- FirefoxTest -->
    <test name="ChromeTest" duration-ms="56512" started-at="2016-02-03T07:37:14Z" finished-at="2016-02-03T07:38:10Z">
      <class name="com.mycompany.autotest.TestNGTest">
        <test-method status="PASS" signature="setUp(java.lang.String)[pri:0, instance:com.mycompany.autotest.TestNGTest@1efbd816]" name="setUp" is-config="true" duration-ms="3427" started-at="2016-02-03T14:37:14Z" finished-at="2016-02-03T14:37:17Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[Chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="testAuto()[pri:0, instance:com.mycompany.autotest.TestNGTest@1efbd816]" name="testAuto" duration-ms="52809" started-at="2016-02-03T14:37:17Z" finished-at="2016-02-03T14:38:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAuto -->
        <test-method status="FAIL" signature="tearDown()[pri:0, instance:com.mycompany.autotest.TestNGTest@1efbd816]" name="tearDown" is-config="true" duration-ms="0" started-at="2016-02-03T14:38:10Z" finished-at="2016-02-03T14:38:10Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[java.lang.AssertionError: expected [KẾT QUẢ CHIẾN DỊCH123] but found [KẾT QUẢ CHIẾN DỊCH]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: java.lang.AssertionError: expected [KẾT QUẢ CHIẾN DỊCH123] but found [KẾT QUẢ CHIẾN DỊCH]
	at org.testng.Assert.fail(Assert.java:94)
	at com.mycompany.autotest.TestNGTest.tearDown(TestNGTest.java:272)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
	at org.testng.internal.TestMethodWorker.invokeAfterClassMethods(TestMethodWorker.java:225)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:114)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:281)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:121)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.mycompany.autotest.TestNGTest -->
    </test> <!-- ChromeTest -->
  </suite> <!-- TestSuite -->
</testng-results>
